# Site settings
title: Mohcine Chraibi
description: "A blog about Mohcine Chraibi ..."
url: "http://chraibi.github.io"
baseurl: ""
# User settings
username: Mohcine Chraibi
user_title: Mohcine Chraibi
email: mohcine@chraibi.de       
twitter_username: MohcineChraibi
github_username:  chraibi
gplus_username:  m.chraibi
disqus_username: m.chraibi

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: none
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
 # - title: series
 #   url: /series
 # - title: tags
 #   url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: JuPedSim
    url: http://www.jupedsim.org
  - name: cellular automata
    url: https://github.com/chraibi/cellular_automata
  - name: BaSiGo
    url: http://www.fz-juelich.de/ias/jsc/EN/Research/ModellingSimulation/CivilSecurityTraffic/Projects/BaSiGo/_node.html
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
# UA-17686252-1 