# Site settings
title: Mohcine Chraibi
description: "A blog about Mohcine Chraibi ..."
#baseurl: "/space-jekyll-template" # the subpath of your site
url: "http://chraibi.github.io"

# User settings
username: Mohcine Chraibi
user_title: Mohcine Chraibi
email: mohcine@chraibi.de       
twitter_username: MohcineChraibi
github_username:  chraibi
#gplus_username:  m.chraibi
#disqus_username: loremipsum

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/


# html minify
compress_html:
  clippings: all
  comments: all
  endings: []
  profile: false

# Links to include in menu navigation
links:
  - title: home
    url: /
  - title: my posts
    url: /posts
 # - title: series
 #   url: /series
  - title: tags
    url: /tags
  - title: about me
    url: /about
# projects in header index
projects:
  - name: JuPedSim
    url: http://www.jupedsim.org
  - name: Cellular automata vim-frontend
    url: https://github.com/chraibi/cellular_automata
  - name: BaSiGo
    url: http://www.fz-juelich.de/ias/jsc/EN/Research/ModellingSimulation/CivilSecurityTraffic/Projects/BaSiGo/_node.html
# exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
